---
- name: Set fact for {{ ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: Create cluster install dir
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ openshift_worker_dir }}"

- name: Get the RHCOS image name
  ansible.builtin.find:
    paths: "{{ ansible_user_dir }}/.cache/agent/image_cache"
    patterns: "*.iso"
  register: iso_files

- name: Generate worker configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ openshift_worker_dir }}/{{ item }}"
    mode: '0644'
  with_items:
    - custom-config.nmconnection
    - init-worker.ign

- name: pull worker ignition file from master
  shell: |
     oc extract -n openshift-machine-api secret/worker-user-data --keys=userData --to=-  > {{ openshift_worker_dir }}/worker.ign

- name: Merge pulled ignition with one pulled from master
  ansible.builtin.shell: |
    python3 -c "
    import json

    # Load two Ignition files
    with open('init-worker.ign') as f1, open('worker.ign') as f2:
        ignition1 = json.load(f1)
        ignition2 = json.load(f2)

    # Merge Ignition JSON objects
    def merge_ignition(ign1, ign2):
        merged = ign1
        for key in ign2:
            if key in merged:
                # Append lists like files, systemd units
                if isinstance(merged[key], list):
                    merged[key].extend(ign2[key])
                # Recursively merge dictionaries
                elif isinstance(merged[key], dict):
                    merged[key] = merge_ignition(merged[key], ign2[key])
            else:
                merged[key] = ign2[key]
        return merged

    merged_ignition = merge_ignition(ignition1, ignition2)

    # Write the merged Ignition file
    with open('merged-worker.ign', 'w') as f:
        json.dump(merged_ignition, f, indent=4)
    "
  args:
    chdir: "{{ openshift_worker_dir }}"

- name: Remove any previous iso generated
  ansible.builtin.file:
    path: "{{ openshift_worker_iso }}"
    state: absent

- name: Run coreos-installer iso customize
  command:
    cmd: coreos-installer iso customize --network-keyfile {{ openshift_worker_dir }}/custom-config.nmconnection --dest-ignition {{ openshift_worker_dir}}/merged-worker.ign --dest-device /dev/{{ disk_type }} {{ iso_files.files[0].path }} -o {{ openshift_worker_iso }} 
 
- name: next steps
  debug: 
    msg: mount the iso "{{ openshift_worker_iso }}" on idrac, and it will fully install and approve

- name: Pause for 3 minutes to allow time to mount iso
  ansible.builtin.pause:
    minutes: 3

- name: Auto approve the worker node certificate signing request (CSR) when its up
  shell: |
      CSR=0
      I=0

      while [[ $CSR -ne 3 ]]; do
        # Fetch the list of CSRs and filter for worker node CSRs
        csr_list=$(oc get csr -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.username}{"\t"}{.status.conditions[*].type}{"\n"}{end}')

        # Extract pending worker CSRs (worker nodes often have the subject "system:node:<worker-node-name>")
        pending_worker_csrs=$(echo "$csr_list" | grep -v 'Approved')

        # Extract approved worker CSRs
        approved_worker_csrs=$(echo "$csr_list" | grep "system:node:worker" | grep 'Approved')

        # Count approved worker CSRs
        CSR=$(echo "$approved_worker_csrs" | wc -l)

        I=$((I+1))

        # Extract the CSR name for pending worker nodes
        CERT=$(echo "$pending_worker_csrs" | awk '{print $1}')

        if [[ -n $CERT ]]; then
          # Approve the CSR
          oc get csr -o go-template='{% raw %}{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}{% endraw %}' | xargs --no-run-if-empty oc adm certificate approve
          #oc adm certificate approve $CERT
          echo "Approved CSR for worker node: $CERT"
        else
          echo "No pending worker CSRs detected on iteration $I"
        fi
          sleep 30s
      done

