- name: "Create Directories"
  ansible.builtin.file:
    mode: '0774'
    path: '{{ item }}'
    state: directory
    owner: "{{ ansible_user_id }}"
    group: wheel
  with_items:
      - "{{ ansible_user_dir }}/.docker/"
      - "{{ registry_volume }}/data"
      - "{{ registry_volume }}/auth"
      - "{{ registry_volume }}/certs"
      - "{{ ansible_user_dir }}/.config/systemd/user"
  become: true

- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: "Generate Registry Basic Auth" ## community.general.htpasswd (requires passlib>=1.6)
  ansible.builtin.command:
    cmd: htpasswd -Bbn {{ registry_username }} {{ registry_password }}
  register: bcrypt_htpasswd

- name: "Write Registry htpasswd credential config"
  ansible.builtin.copy:
    content: '{{ bcrypt_htpasswd.stdout }}'
    dest: '{{ registry_volume }}/auth/htpasswd'
    mode: 0760

- name: Generate RSA private key
  community.crypto.openssl_privatekey:
    path: "{{ registry_volume }}/certs/domain.key"
    size: 4096
    type: RSA
    cipher: null
    passphrase: null

- name: Generate CSR with SANs
  community.crypto.openssl_csr:
    privatekey_path: "{{ registry_volume }}/certs/domain.key"
    path: "{{ registry_volume }}/certs/doamin.csr"
    subject_alt_name: DNS:{{ ansible_fqdn }},DNS:{{ ansible_hostname }},DNS:localhost,IP:{{ ipv4_address | first }}

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ registry_volume }}/certs/domain.crt"
    privatekey_path: "{{ registry_volume }}/certs/domain.key"
    csr_path: "{{ registry_volume }}/certs/doamin.csr"
    provider: selfsigned
    owner: "{{ ansible_user_id }}"
    group: wheel

- name: Load registry image to podman storage
  containers.podman.podman_load:
    input: "{{ common_openshift_oc_mirror_dir }}/registry.tar"

- name: Generate systemd file for {{ registry_pod_name }}
  containers.podman.podman_container:
    name: "{{ registry_pod_name }}"
    privileged: false
    image: docker.io/library/registry:latest
    state: present
    ports: "{{ common_registry_port }}:5000"
    volume:
      - "{{ registry_volume }}/data:/var/lib/registry:z"
      - "{{ registry_volume }}/auth:/auth:z"
      - "{{ registry_volume }}/certs:/certs:z"
    env:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"
      REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED: "true"
    generate_systemd:
      path: "{{ ansible_user_dir }}/.config/systemd/user/"
      names: true
      time: 1

- name: Allows Service to Start without user logging in
  command:
    cmd: loginctl enable-linger "{{ lookup('env','USER') }}"
  become: true

- name: Enforce registry pod to run
  ansible.builtin.systemd_service:
    name: "container-{{ registry_pod_name }}.service"
    state: started
    enabled: true
    daemon_reload: true
    scope: user

- name: Ensure firewalld is configured for port {{ common_registry_port }}
  firewalld:
    port: 5000/tcp
    immediate: true
    permanent: true
    state: enabled
  become: true

- name: "Login to registry"
  ansible.builtin.command:
    cmd: podman login https://{{ ipv4_address | first  }}:{{ common_registry_port }} --username {{ registry_username }} --password {{ registry_password }} --tls-verify=false
  register: registry_logedin
  retries: 5
  delay: 2
  until: registry_logedin.rc == 0

- name: "copy /run/user/1000/containers/auth.json to {{ ansible_user_dir }}/.docker/config.json"
  ansible.builtin.copy:
    src: /run/user/1000/containers/auth.json
    dest: "{{ ansible_user_dir }}/.docker/config.json"
    backup: true
    
