---
- name: Create cluster directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ common_openshift_client_bin }}"
    - "{{ common_openshift_oc_mirror_dir }}"
    - "{{ common_openshift_download_dir }}"
    - "{{ common_openshift_download_dir }}/collections"

- name: Check if openshift-install is available
  ansible.builtin.shell: "openshift-install version"
  register: install_check
  ignore_errors: true
  changed_when: false  # Prevent the playbook from being marked as changed if the command is missing
  failed_when: false   # Prevent failure when the command is not found

- name: Set tools to download if openshift-install is missing or incorrect
  ansible.builtin.debug: 
    msg: Checking version for openshift-install
  when: 
    - install_check.rc != 0 or "common_openshift_release not in install_check.stdout"
  notify:
    - Download_oc_tools
    - Extract_oc_tools
    - Remove_oc_tools_tar

- name: Check if "trident" binary is present
  ansible.builtin.stat:
    path: /usr/bin/trident
  failed_when: false
  notify:
    - Download_trident
    - Extract_trident_binary
    - Move_tridentctl_to_proper_location
    - Remove_trident-installer/tridentctl

- name: Check if {{ item }} binary is present
  ansible.builtin.stat:
    path: /usr/bin/{{ item }}
  with_items:
    - butane
    - helm
  failed_when: false
  notify:
    - Download {{ item }}

- name: Check for saved registry
  ansible.builtin.stat:
    path:  "{{ common_openshift_oc_mirror_dir }}/registry.tar"
  failed_when: false
  notify:
    - Pull_registry_image
    - Save_registry_image

- name: Check for pre-staged RHCOS image
  ansible.builtin.find:
    paths: "{{ ansible_user_dir }}/.cache/agent/image_cache"
    patterns: "*.iso"
  failed_when: false
  notify:
    - Detect_RHCOS_image_URL
    - Parse_RHCOS_image_URL
    - Downlaod_RHCOS_image

- name: Download required ansible collections
  ansible.builtin.command: 
    cmd: ansible-galaxy collection download --requirements-file ../collections/requirements.yml --download-path {{ common_openshift_download_dir }}/collections

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- include_tasks: pull_images.yml
  when: content_generation_pull_mirror | bool
