---
- name: Create cluster directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ common_openshift_client_bin }}"
    - "{{ common_openshift_oc_mirror_dir }}"
    - "{{ common_openshift_download_dir }}"
    - "{{ common_openshift_download_dir }}/collections"
    - "{{ common_openshift_client_bin }}"
    - "{{ common_openshift_oc_mirror_dir }}"
    - "{{ common_openshift_download_dir }}"
    - "{{ common_openshift_download_dir }}/collections"

- name: Check if openshift-install is available
  ansible.builtin.shell: "openshift-install version"
  register: install_check
  ignore_errors: true
  changed_when: false  # Prevent the playbook from being marked as changed if the command is missing
  failed_when: false   # Prevent failure when the command is not found

- name: Set tools to download if openshift-install is missing or incorrect
  ansible.builtin.debug: 
    msg: incorrect version found
  when: 
    - install_check.rc != 0 or "common_openshift_release not in install_check.stdout"
  notify:
    - Download oc tools
    - Extract oc tools
    - Remove oc tools tar

- meta: flush_handlers

- name: Check if "trident" binary is present
  ansible.builtin.stat:
    path: /usr/bin/trident
  failed_when: false
  notify:
    - Downlaod trident
    - Extract trident binary
    - Move tridentctl to proper location
    - Remove trident-installer/tridentctl

- name: Check if {{ item }} binary is present
  ansible.builtin.stat:
    path: /usr/bin/{{ item }}
  with_items:
    - butane
    - helm
  failed_when: false
  notify:
    - Downlaod {{ item }}

- name: Check for saved registry
  ansible.builtin.stat:
    path:  "{{ common_openshift_oc_mirror_dir }}/registry.tar"
  failed_when: false
  notify:
    - Pull registry image
    - Save registry image

- name: Check for pre-staged RHCOS image
  ansible.builtin.find:
    paths: "{{ ansible_user_dir }}/.cache/agent/image_cache"
    patterns: "*.iso"
  failed_when: false
  notify:
    - Detect RHCOS image URL
    - Parse RHCOS image URL
    - Downlaod RHCOS image
  
- name: Download required ansible collections
  ansible.builtin.command: 
    cmd: ansible-galaxy collection download --requirements-file ../collections/requirements.yml --download-path {{ common_openshift_download_dir }}/collections

- include_tasks: pull_images.yml
  when: content_generation_pull_mirror | bool
