---
- name: Create cluster directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ common_openshift_client_bin }}"
    - "{{ common_openshift_oc_mirror_dir }}"
    - "{{ common_openshift_download_dir }}"
    - "{{ common_openshift_download_dir }}/collections"

- name: Check if openshift-install is available
  ansible.builtin.shell: "openshift-install version"
  register: install_check
  ignore_errors: true
  changed_when: 'install_check.rc != 0 or "common_openshift_release not in install_check.stdout"'
  notify:
    - Download_oc

- meta: flush_handlers

- name: Check if "trident" binary is present
  ansible.builtin.stat:
    path: /usr/bin/trident
  register: trident
  failed_when: false
  changed_when: 'trident.rc != 0'
  notify:
    - Download_trident

- name: Check if butane binary is present
  ansible.builtin.stat:
    path: /usr/bin/butane
  failed_when: false
  register: butane
  changed_when: 'butane.rc != 0'
  notify:
    - Download butane

- name: Check if helm binary is present
  ansible.builtin.stat:
    path: /usr/bin/helm
  failed_when: false
  register: helm
  changed_when: 'helm.rc != 0'
  notify:
    - Download helm

- name: Check for saved registry
  ansible.builtin.stat:
    path:  "{{ common_openshift_oc_mirror_dir }}/registry.tar"
  register: registry
  changed_when: 'registry.rc != 0'
  failed_when: false
  notify:
    - Registry_image

- name: Check for pre-staged RHCOS image
  ansible.builtin.find:
    paths: "{{ ansible_user_dir }}/.cache/agent/image_cache"
    patterns: "*.iso"
  register: rhcos
  changed_when: 'rhcos.rc != 0'
  failed_when: false
  notify:
    - rhcos_image

- name: Download required ansible collections
  ansible.builtin.command: 
    cmd: ansible-galaxy collection download --requirements-file ../collections/requirements.yml --download-path {{ common_openshift_download_dir }}/collections

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- include_tasks: pull_images.yml
  when: content_generation_pull_mirror | bool
