namespace: "ocp4"
name: "disconnected"
version: "0.1.1"
readme: "README.md"
authors:
    - "Matt Riensch (example@gmail.com)"
dependencies:
    "dellemc.openmanage": ">=1.0.0"
    "containers.podman": "*"
license:
    - "MIT"
repository: "https://github.com/mriensch/ocp4-disconnected-agent.git"
