namespace: "ocp4"
name: "disconnected"
version: "0.1.1"
readme: "README.md"
authors:
    - "Matt Riensch (example@gmail.com)"
dependencies:
    "dellemc.openmanage": "=9.5.0"
    "containers.podman": "*"
    "ansible.posix": "1.5.2"
    "cisco.nxos": "*"
    "community.general": "*"
license:
    - "MIT"
repository: "https://github.com/mriensch/ocp4-disconnected-agent.git"
