# Defaults main.yml for common role

common_openshift_dir: "{{ ansible_user_dir }}/content"
common_openshift_download_dir: "{{ common_openshift_dir }}/downloads"
common_openshift_cluster_install_dir: "{{ common_install_dir }}/install-{{ ansible_date_time.date }}"
common_openshift_oc_mirror_dir: "{{ common_openshift_dir }}/images"
common_openshift_client_bin: "{{ common_openshift_dir }}/bin"
common_openshift_interface: eno1
common_openshift_release: 4.14.16
common_openshift_download_base_url: https://mirror.openshift.com/pub/openshift-v4/{{ openshift_bastion_platform }}/clients
common_cluster_domain: example.com
common_openshift_bastion_platform: x86_64


collection_path: "{{ ansible_user_dir }}/.ansible/collections/ansible_collections/ansible/netcommon"
common_install_dir: "{{ ansible_user_dir }}"
common_ip_space: 24
common_subnet_mask: 24
common_gateway_ip: '{{ common_ip_space }}.1'
common_ssh_key: "{{ ansible_user_dir + '/.ssh/id_rsa' }}"
common_registry_port: 5000

common_previous_openshift_release: 4.14.16
common_trident_version: v24.06.0


#common_ip_space: 192.168.169
#common_nodes:
#  - name: master-0
#    ip: '17'
#    mac: be:47:95:d0:01:51
#  - name: master-1
#    ip: '18'
#    mac: be:47:95:d0:01:52
#  - name: master-2
#    ip: '19'
#    mac: be:47:95:d0:01:53
#  - name: worker-0
#    ip: '20'
#    mac: be:47:95:d0:01:54

