---
- name: Create cluster install dir
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ openshift_cluster_install_dir }}"
    - "{{ openshift_cluster_config_dir }}"

- name: Generate RSA ssh keys
  ansible.builtin.command:
    cmd: "ssh-keygen -t rsa -b 2048 -f {{ ssh_key }} -N ''"

- name: Generate agent-config.yaml
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ openshift_cluster_install_dir }}/{{ item }}"
    mode: '0644'
  with_items:
   - install-config.yaml
   - agent-config.yaml

- name: Create copys of agent-config and install configuration
  ansible.builtin.copy:
    src: "{{ openshift_cluster_install_dir }}/{{ item }}"
    dest: "{{ openshift_cluster_install_dir }}/{{ item }}-copy"
    remote_src: yes
  with_items:
   - install-config.yaml
   - agent-config.yaml

- name: Generate ISO
  ansible.builtin.command:
    cmd: openshift-install agent create image --dir {{ openshift_cluster_install_dir }}

- name: Move generated ISO to webroot
  ansible.builtin.copy:
    src: "{{ openshift_cluster_install_dir}}/agent.x86_64.iso"
    dest: /var/www/html/
    remote_src: true
  become: true
  tags: idrac
