- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /usr/bin
    state: directory
    mode: '0555'
  become: true

- name: Move binaries to destination directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/bin/
    mode: '0755'
    remote_src: yes
  become: true
  with_fileglob:
    - "{{ openshift_client_bin }}/*"