---
- name: Set fact for {{ ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: push images into registry
  ansible.builtin.command:
    cmd: "oc-mirror --from {{ openshift_oc_mirror_dir }}/{{ item }} \
      docker://{{ ipv4_address | first }}:{{ registry_port }} --dest-skip-tls"
  register: cluster_images
  retries: 5
  delay: 10
  until: cluster_images.rc == 0
  with_items: 
      - cluster-images
      - operators