---
- name: Move generated ISO to webroot
  ansible.builtin.copy:
    src: "{{ common_openshift_cluster_install_dir}}/agent.x86_64.iso"
    dest: /var/www/html/
    remote_src: true
  become: true
  
- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: Insert image file using HTTP.
  delegate_to: localhost
  dellemc.openmanage.idrac_virtual_media:
    idrac_ip: "{{ item.ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    force: true
    virtual_media:
      - insert: true
        image: "http://{{ ipv4_address | first }}/agent.x86_64.iso"
        media_type: "DVD"
  loop: "{{ idracs }}"

- name: Boot Once via CD
  delegate_to: localhost
  dellemc.openmanage.idrac_boot:
    idrac_ip: "{{ item.ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    boot_source_override_target: cd
    boot_source_override_enabled: once
    reset_type: force_restart
  loop: "{{ idracs }}"
