---
- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: push {{ image_source }} images into registry
  ansible.builtin.command:
    cmd: "oc-mirror --from {{ common_openshift_oc_mirror_dir }}/{{ image_source }} \
      docker://{{ ipv4_address | first }}:{{ common_registry_port }}"
  register: push_images
  retries: 5
  delay: 10
  until: push_images.rc == 0