---
- name:  Open port {{ media_share_webserver_port }} on the firewall
  firewalld: 
    port: "{{ media_share_webserver_port }}/tcp"
    permanent: no
    immediate: yes
    state: enabled
  become: true
  
- name: Create the temporary webserver | runs in background via tmux
  shell:
    cmd: 'tmux new-session -d -s temp-webserver python3 -m http.server'
  args:
    chdir: "{{ common_openshift_cluster_install_dir }}"

- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: Insert image file using HTTP.
  delegate_to: localhost
  dellemc.openmanage.idrac_virtual_media:
    idrac_ip: "{{ media_share_idracs.ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    force: true
    virtual_media:
      - insert: true
        image: "http://{{ ipv4_address | first }}:{{ media_share_webserver_port }}/agent.x86_64.iso"
        media_type: "DVD"

- name: Boot Once via CD
  delegate_to: localhost
  dellemc.openmanage.idrac_boot:
    idrac_ip: "{{ media_share_idracs.ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    boot_source_override_target: cd
    boot_source_override_enabled: once
    reset_type: force_restart
