- name: Generate RSA ssh keys
  community.crypto.openssh_keypair:
    path: "{{ common_ssh_key }}"
    size: 2048
    type: rsa
    state: present

- name: Create git user
  ansible.builtin.user:
    name: git
    shell: /bin/bash
    home: /home/git
    createhome: true
    state: present
    password: !
  become: true

- name: Create directories needed
  ansible.builtin.file:
    path: /home/git/.ssh
    state: directory
    owner: git
    group: git
    mode: '0700'
  become: true
  
- name: Copy generated ssh key to authorized key
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    dest: /home/git/.ssh/authorized_keys
    mode: '0600'
    owner: git
    group: git
  become: true

- name: create base repo directory 
  ansible.builtin.file:
    path: "{{ git_user_repo_dir }}"
    state: directory
    owner: git
    group: git
    mode: '0755'
  become: true

- name: Ensure ownership is set to git:git
  ansible.builtin.file:
    path: "/home/git"
    state: directory
    owner: git
    group: git
    recurse: yes
  become: true

- name: Find directories in the git repos directory
  ansible.builtin.find:
    paths: "{{ common_git_repos_dir }}"
    recurse: no
    file_type: directory
  register: git_directories

- name: Copy bare git repos to git user directory
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ git_user_repo_dir }}"
    remote_src: true
    mode: '0755'
    owner: git
    group: git
    directory_mode: '0755'
  with_items: "{{ git_directories.files }}"
  become: true
