- name: Generate RSA ssh keys
  ansible.builtin.command:
    cmd: "ssh-keygen -t rsa -b 2048 -f {{ ssh_key }} -N ''"
    creates: "{{ ssh_key}}"
  register: ssh_keygen
  changed_when: ssh_keygen.rc == 0

- name: Create git user
  ansible.builtin.user:
    name: git
    shell: /bin/bash
    home: /home/git
    createhome: true
    state: present
    password: !
  become: true

- name: Create directories needed
  ansible.builtin.file:
    path: /home/git/.ssh
    state: directory
    owner: git
    group: git
    mode: '0700'
  become: true
  
- name: Copy generated ssh key to authorized key
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    dest: /home/git/.ssh/authorized_keys
    mode: '0600'
    owner: git
    group: git
  become: true

- name: create base repo directory 
  ansible.builtin.file:
    path: /home/git/repos
    state: directory
    owner: git
    group: git
    mode: '0755'
  become: true

- name: Create all inital repos
  ansible.builtin.command:
    cmd: git init --bare {{ item }}
  args:
    chdir: /home/git
  with_items:
    - day2
    - apps
  become: true

- name: Ensure ownership of repositories is set to git:git
  ansible.builtin.file:
    path: "/home/git"
    state: directory
    owner: git
    group: git
    recurse: yes
  become: true