- name: Ensure required packages are installed
  ansible.builtin.package:
    name: nmstate,openssl,httpd-tools,podman,git,python3-jmespath
    state: present
  become: true

- name: Create RHCOS iso prestage directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.cache/agent/image_cache"
    state: directory

- name: Prestage RHCOS iso to {{ ansible_user_dir }}/.cache/agent/image_cache
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.cache/agent/image_cache"
  with_fileglob:
    - "{{ openshift_download_dir }}/*iso"