---
- name: Create private key for CA
  community.crypto.openssl_privatekey:
    path: /etc/pki/ca-trust/source/anchors/ca.key
  become: true

- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: Generate an OpenSSL Certificate Signing Request with subjectAltName extension
  community.crypto.openssl_csr:
    path: /etc/pki/ca-trust/source/anchors/ca.csr
    privatekey_path: /etc/pki/ca-trust/source/anchors/ca.key
    subject_alt_name: DNS:{{ ansible_fqdn }},DNS:{{ ansible_hostname }},DNS:localhost,IP:{{ ipv4_address | first }}
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  become: true

- name: Create self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/pki/ca-trust/source/anchors/ca.cer
    privatekey_path: /etc/pki/ca-trust/source/anchors/ca.key
    csr_path: /etc/pki/ca-trust/source/anchors/ca.csr
    provider: selfsigned
  become: true
  register: create_ca

- name: Update system trust with created ca
  ansible.builtin.command: "update-ca-trust"
  become: true
  when: create_ca is changed