---
- name: Create private key for CA
  community.crypto.openssl_privatekey:
    path: /etc/pki/ca-trust/source/anchors/ca.key
  become: true
  register: create_key
 
- name: Generate an OpenSSL Certificate Signing Request for the CA
  community.crypto.openssl_csr:
    path: /etc/pki/ca-trust/source/anchors/ca.csr
    privatekey_path: /etc/pki/ca-trust/source/anchors/ca.key
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  become: true
  register: create_csr

- name: Create the CA self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/pki/ca-trust/source/anchors/ca.cer
    privatekey_path: /etc/pki/ca-trust/source/anchors/ca.key
    csr_path: /etc/pki/ca-trust/source/anchors/ca.csr
    provider: selfsigned
    group: wheel
    mode: '0640'
  become: true
  register: create_ca
  when: create_key is changed and create_csr is changed

- name: Update system trust with created CA
  ansible.builtin.command: "update-ca-trust"
  become: true
  when: create_ca is changed