---
# defaults file for add-worker role

worker_iso_openshift_worker_dir: "{{ common_openshift_cluster_install_dir }}"
worker_iso_disk_type: "sda"
worker_iso_openshift_worker_iso: "{{ worker_iso_openshift_worker_dir }}/coreos-worker.iso"