---
# tasks file for openshift-gitops

- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: Generate configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ common_openshift_download_dir }}/{{ item }}"
    mode: '0644'
  with_items:
   - gitops-repo.yaml
   - gitops-subscription.yaml